// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ3GRch8W5s0Hu0xhpbYrG3-oh4sysZRo',
    appId: '1:553703496495:web:a7d66d37b03421db9e1fda',
    messagingSenderId: '553703496495',
    projectId: 'utmsports-620f9',
    authDomain: 'utmsports-620f9.firebaseapp.com',
    storageBucket: 'utmsports-620f9.firebasestorage.app',
    measurementId: 'G-K50GK6RMZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhTLOHoN70vIn_tcoQnysMivBBOOTGt4',
    appId: '1:553703496495:android:1084d5521e6055b29e1fda',
    messagingSenderId: '553703496495',
    projectId: 'utmsports-620f9',
    storageBucket: 'utmsports-620f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJWjmNLk-sEqKZKBIdb9xLAeT7Bv3ieY',
    appId: '1:553703496495:ios:fea5fa9d820f77459e1fda',
    messagingSenderId: '553703496495',
    projectId: 'utmsports-620f9',
    storageBucket: 'utmsports-620f9.firebasestorage.app',
    iosBundleId: 'com.example.utmsportsplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJWjmNLk-sEqKZKBIdb9xLAeT7Bv3ieY',
    appId: '1:553703496495:ios:fea5fa9d820f77459e1fda',
    messagingSenderId: '553703496495',
    projectId: 'utmsports-620f9',
    storageBucket: 'utmsports-620f9.firebasestorage.app',
    iosBundleId: 'com.example.utmsportsplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ3GRch8W5s0Hu0xhpbYrG3-oh4sysZRo',
    appId: '1:553703496495:web:2f10db50b6bf19ec9e1fda',
    messagingSenderId: '553703496495',
    projectId: 'utmsports-620f9',
    authDomain: 'utmsports-620f9.firebaseapp.com',
    storageBucket: 'utmsports-620f9.firebasestorage.app',
    measurementId: 'G-Y387RZ4LF1',
  );
}
